### PR TITLE
Mobile App

### PR DESCRIPTION
**Pull request by joaopedroft**
Initial content for cordova mobile app.

### CODE REVIEW

**Comment by andresilva** [comment]
Can you give a brief description on how to run this (I use iOS). Or maybe just point me to some tutorials. 👍

**Comment by joaopedroft** [comment]
This link shows how to create a simple cordova app:
https://cordova.apache.org/docs/en/latest/guide/cli/index.html

And this one shows how to deploy to ios device with xcode:
https://cordova.apache.org/docs/en/latest/guide/platforms/ios/index.html

**Comment by andresilva** [comment]
works

Why didn't you add the other cordova related files?

**Comment by joaopedroft** [comment]
Nice, i didn't put the rest of the files because they are generated on each cordova app creation.
I could put the config.xml file for people see some extra configuration like the app icon, name and package name.

**Comment by joaopedroft** [comment]
screenshot_20160503-163751

Agora com o logo fica assim.

**Comment by luismfonseca** [comment]
@andrebeat I think that this is now ok to merge, can you re-review?

It would be nice to support OAuth in the future - is it hard to implement this using Cordova?

**Comment by joaopedroft** [comment]
I have been thinking about it, but is not hard to implement. 
The must difficult task maybe is not let the user going to outside browser to accept slack login permissions. 
As soon as I have time available I will try

**Comment by andresilva** [comment]
I've made some changes and created a new PR (#13) to track those changes so I'll close this one.

**Pull request closed without merging**
